services:
  backend:
    build: ./server
    container_name: server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped


volumes:
  mongo-data:
  ollama-data:
